services:
  frontend:
    build:
      context: .
      dockerfile: frontend/.devcontainer/Dockerfile
    command: sleep infinity
    env_file:
      - .env
    ports:
      - 3001:3000
    volumes:
      - .:/app
  backend:
    build:
      context: .
      dockerfile: backend/.devcontainer/Dockerfile
    command: sleep infinity
    env_file:
      - .env
    ports:
      - 3002:3000
      - 8000:8000
    volumes:
      - .:/app
