services:

  frontend:
    build:
      context: .
      dockerfile: frontend/.devcontainer/Dockerfile
    command: yarn run dev
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - 3001:3000
    volumes:
      - .:/app

  backend:
    build:
      context: .
      dockerfile: backend/.devcontainer/Dockerfile
    command: sleep infinity
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - 3002:3000
      - 8000:8000
    volumes:
      - .:/app

  mysql:
    image: mysql:8
    env_file:
      - .env
    command: mysqld --default_authentication_plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
