[package]
edition = "2021"
name = "db"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = {version = "0.9.3", features = ["debug-print", "sqlx-mysql", "runtime-tokio-native-tls", "macros"]}
